### ISSUE TITLE
Handhelds Grenades causing crashes

### ISSUE THREAD

**Issue by monkstick-git** [Bubbus/ACF-SWEPs#2]
Apparently,  making nukes (ammo creates and a grenade) causes server side crashes.  Friend of mine will fill in more information shortly.

**Comment by Bubbus** [comment]
Does this error occur with this commit? 50c822fcaf1df0d8d10cdcf48278accd6a6034ff

**Comment by monkstick-git** [comment]
That I do not know,  I didn't notice the recent Commit.  Let me test.

**Comment by Bubbus** [comment]
Hold on for a minute, i just noticed an issue with it...

**Comment by monkstick-git** [comment]
Will do

**Comment by Bubbus** [comment]
Got it fb7ae3791cb3107676426f267769510d862f5dbf

**Comment by monkstick-git** [comment]
Shall test it for you now

**Comment by monkstick-git** [comment]
http://puu.sh/hIroF/a6f2c3e80d.png

Apparently if you throw a grenade,  nothing happens.  If you try to blow it up with wire,  this happens.

**Comment by Bubbus** [comment]
Right, I'll take a look at that some time tonight.  Thanks.

**Comment by monkstick-git** [comment]
No problem

**Comment by monkstick-git** [comment]
Satchel charges don't work either

**Comment by Bubbus** [comment]
Fixed both in d2891eaa17f0a1624149c4ba6d43fb23a644f5ab, try now?

**Comment by Bubbus** [comment]
I think this is fixed, let me know if the issue persists.
